CREATE TABLE IF NOT EXISTS organization
(
    org_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS custom_rev_info
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp BIGINT,
    username  VARCHAR
);

CREATE TABLE IF NOT EXISTS organization_aud
(
    org_id  BIGINT  NOT NULL,
    REV     INTEGER NOT NULL,
    REVTYPE int,
    REVEND  INTEGER,
    name    VARCHAR,
    PRIMARY KEY (org_id, rev),
    CONSTRAINT fk_revision FOREIGN KEY (REV) REFERENCES custom_rev_info (id)
);

