CREATE TABLE IF NOT EXISTS organization
(
    org_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS revision_info
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp BIGINT,
    user_name VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS organization_audit
(
    org_id  BIGINT  NOT NULL,
    rev     INTEGER NOT NULL,
    revtype INTEGER,
    revend  INTEGER,
    name    VARCHAR(32),
    PRIMARY KEY (org_id, rev),
    CONSTRAINT fk_revision FOREIGN KEY (rev) REFERENCES revision_info (id)
);

