spring:
  mustache:
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/atlantis
    username: atlantis
    password: Wecandoit
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    enabled: false
    clean-disabled: true
    locations: classpath:db/migration/public/
    init-sqls: CREATE IF NOT EXISTS flyway_history_schema
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      org:
        hibernate:
          envers:
            audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
    show-sql: true
logging:
  file:
    path: logs
    max-size: 10MB

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %u %t %m %U %q %s'
      max-days: 1
      rename-on-rotate: true
      prefix: access
      directory: ../logs
    basedir: web
  http2:
    enabled: true
  compression:
    enabled: true
---
spring:
  profiles: development
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: false
  flyway:
    enabled: true
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
---
