CREATE TABLE IF NOT EXISTS auth_user
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name     VARCHAR(32)   UNIQUE  NOT NULL,
    password      VARCHAR(72)          NOT NULL,
    name          VARCHAR(32)           NOT NULL,
    mobile_number BIGINT        UNIQUE,
    email         VARCHAR       UNIQUE,
    active        boolean default true,
    org_id        BIGINT,
    user_type     SMALLINT,
    CONSTRAINT fk_organization FOREIGN KEY (org_id) REFERENCES public.organization (org_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS role
(
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(32) UNIQUE NOT NULL,
    description VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS privilege
(
    privilege_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES role (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES auth_user (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS role_privileges
(
    role_id      BIGINT NOT NULL,
    privilege_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, privilege_id),
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES role (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_privilege FOREIGN KEY (privilege_id) REFERENCES privilege (privilege_id) ON DELETE CASCADE
);
