CREATE TABLE IF NOT EXISTS category_group
(
    group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR UNIQUE NOT NULL,
    group_id    BIGINT,
    CONSTRAINT fk_category_group FOREIGN KEY (group_id) REFERENCES category_group (group_id)
);